// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SqlRepositoryAdapter;

#nullable disable

namespace SqlRepositoryAdapter.Migrations
{
    [DbContext(typeof(GpzDbCtx))]
    partial class GpzDbCtxModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressNumberEntityId")
                        .HasColumnType("int");

                    b.Property<int>("AddressTypeEntityId")
                        .HasColumnType("int");

                    b.Property<int?>("ClientCreditRequestEntityId")
                        .HasColumnType("int");

                    b.Property<string>("Colonia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AddressNumberEntityId");

                    b.HasIndex("AddressTypeEntityId");

                    b.HasIndex("ClientCreditRequestEntityId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.AddressNumberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Exterior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Interior")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddressNumbers");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.AddressTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AddressType");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.ClientCreditRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedPhoneNumber")
                        .HasColumnType("int");

                    b.Property<DateTime>("CaptureDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ClientEntityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfAssigment")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProjectTypeEntityId")
                        .HasColumnType("int");

                    b.Property<int>("RequestTypeEntityId")
                        .HasColumnType("int");

                    b.Property<bool>("Urgent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("ClientEntityId");

                    b.HasIndex("ProjectTypeEntityId");

                    b.HasIndex("RequestTypeEntityId");

                    b.ToTable("ClientCreditRequests");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.ClientEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rfc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.PersonalReferenceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientCreditRequestEntityId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhoneNumberEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientCreditRequestEntityId");

                    b.HasIndex("PhoneNumberEntityId");

                    b.ToTable("PersonalReferences");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.PhoneNumberEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientCreditRequestEntityId")
                        .HasColumnType("int");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("PhoneTypeEntityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ClientCreditRequestEntityId");

                    b.HasIndex("PhoneTypeEntityId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.PhoneTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PhoneType");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.ProjectTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ProjectType");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.RequestTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RequestType");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserProfileId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.UserProfileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.AddressEntity", b =>
                {
                    b.HasOne("SqlRepositoryAdapter.Entities.AddressNumberEntity", "Number")
                        .WithMany()
                        .HasForeignKey("AddressNumberEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlRepositoryAdapter.Entities.AddressTypeEntity", "AddressType")
                        .WithMany()
                        .HasForeignKey("AddressTypeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlRepositoryAdapter.Entities.ClientCreditRequestEntity", "ClientCreditRequestEntity")
                        .WithMany("Addresses")
                        .HasForeignKey("ClientCreditRequestEntityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("AddressType");

                    b.Navigation("ClientCreditRequestEntity");

                    b.Navigation("Number");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.ClientCreditRequestEntity", b =>
                {
                    b.HasOne("SqlRepositoryAdapter.Entities.ClientEntity", "Client")
                        .WithMany()
                        .HasForeignKey("ClientEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlRepositoryAdapter.Entities.ProjectTypeEntity", "ProjectType")
                        .WithMany()
                        .HasForeignKey("ProjectTypeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SqlRepositoryAdapter.Entities.RequestTypeEntity", "RequestType")
                        .WithMany()
                        .HasForeignKey("RequestTypeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("ProjectType");

                    b.Navigation("RequestType");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.PersonalReferenceEntity", b =>
                {
                    b.HasOne("SqlRepositoryAdapter.Entities.ClientCreditRequestEntity", "ClientCreditRequestEntity")
                        .WithMany("PersonalReferences")
                        .HasForeignKey("ClientCreditRequestEntityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SqlRepositoryAdapter.Entities.PhoneNumberEntity", "PhoneNumber")
                        .WithMany()
                        .HasForeignKey("PhoneNumberEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCreditRequestEntity");

                    b.Navigation("PhoneNumber");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.PhoneNumberEntity", b =>
                {
                    b.HasOne("SqlRepositoryAdapter.Entities.ClientCreditRequestEntity", "ClientCreditRequestEntity")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("ClientCreditRequestEntityId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("SqlRepositoryAdapter.Entities.PhoneTypeEntity", "PhoneType")
                        .WithMany()
                        .HasForeignKey("PhoneTypeEntityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ClientCreditRequestEntity");

                    b.Navigation("PhoneType");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.UserEntity", b =>
                {
                    b.HasOne("SqlRepositoryAdapter.Entities.UserProfileEntity", "UserProfile")
                        .WithMany()
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("SqlRepositoryAdapter.Entities.ClientCreditRequestEntity", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("PersonalReferences");

                    b.Navigation("PhoneNumbers");
                });
#pragma warning restore 612, 618
        }
    }
}
